const manual = document.createElement('dialog');
manual.id = 'manual';
manual.setAttribute('aria-labelledby', 'manualTitle');
const keys = (letters, labels) =>
  `<div class="manualKeys">${letters.map((k, i) => `<div><kbd>${k}</kbd><small>${labels[i]}</small></div>`).join('')}</div>`;
manual.innerHTML = `<div class="manualTop"><div><small>FIELD GUIDE / 01</small><h2 id="manualTitle">MACHINEDRUM</h2></div><button id="closeManual" aria-label="Close the manual">✕</button></div>
<div class="manualBody"><section><h3>FX / STEP LOCK</h3><p>The FX page supports per-step locks for D.SEND, R.SEND, TIME, FDBK, D.RET and R.RET. With STEP LOCK on, clicking a cell still toggles its note; select a step and turn a knob — or hold a step and turn a knob — to write a locked value. The next step keeps the base value. The master effects are shared by every track; when two tracks write the same step, the higher-numbered track wins. Reverb DECAY always stays global. CLEAR LOCKS on the FX page removes only that step's FX locks.</p></section><section><h3>LFO / per-track modulation</h3><p>Click LFO next to FX on the screen, then use knobs A–H for wave, destination, speed, depth, phase, sync, mode and on/off. Destinations are pitch, level and filter; depth starts at 0. With SYNC on FREE, speed reads in Hz; every other setting follows BPM. In MODE FREE the phase runs across notes, in TRIG it restarts on each hit. The LFO modulates continuously while a note sounds; parameter edits take effect from the next trigger on. They are saved and restored with the Kit, and are not written into Step Lock.</p></section>
<section><h3>01 / Start with one beat</h3><div class="manualFlow"><span>① Pick a track<small>number keys 1–8</small></span><b>→</b><span>② Light up STEP<small>Z X C V B N M ,</small></span><b>→</b><span>③ Play<small>SPACE</small></span><b>→</b><span>④ Shape the sound<small>drag / scroll the knobs</small></span></div><p>Every Pattern has 16 tracks of 16 steps each. Click a step button to toggle a note, or hold the mouse and drag across several steps to light them in one pass. Start by clearing the current beat with CLEAR PATTERN, then build from kick, snare and hats. Clearing stops playback and removes the notes and parameter locks of the current Pattern; UNDO CLEAR brings back the most recent clear, until the page is reloaded.</p></section>
<section><h3>02 / The keyboard is the step panel</h3><div class="manualLegend"><b>Select a sound</b><span>plain: tracks 1–8 · SHIFT: tracks 9–16</span></div>${keys(['1', '2', '3', '4', '5', '6', '7', '8'], ['BD / FM1', 'SD / FM2', 'CH / CB', 'OH / CY', 'CP / NO', 'LT / SUB', 'HT / PERC', 'RS / MET'])}<div class="manualLegend"><b>Edit one octave of steps</b><span>TAB switches the front / back eight</span></div>${keys(['Z', 'X', 'C', 'V', 'B', 'N', 'M', ','], ['01 / 09', '02 / 10', '03 / 11', '04 / 12', '05 / 13', '06 / 14', '07 / 15', '08 / 16'])}<p><kbd>SHIFT</kbd> + any step key above (in normal step mode): hits <strong>the currently selected sound</strong> rather than eight different pitches. Change track and the hit follows it. M is step 7 / 15, and U is the mute.</p><div class="manualLegend"><b>Switch Pattern</b><span>CTRL + SHIFT + number</span></div>${keys(['1 → A', '2 → B', '3 → C', '4 → D'], ['CTRL + SHIFT', 'CTRL + SHIFT', 'CTRL + SHIFT', 'CTRL + SHIFT'])}<p>Picking another Pattern while playing queues the switch for the next bar.</p></section>
<section><h3>03 / Live playing and recording</h3><div class="manualCards"><article><b>P / PADS</b><p>The eight step keys or the number keys hit their track directly; SHIFT + the same keys hits tracks 9–16. Press P again to return to the steps.</p></article><article><b>R / RECORD</b><p>Turn on live recording and enter PADS. Z X C V B N M , hit BD–RS, SHIFT + those eight keys hits tracks 9–16. While stopped you only audition; press Space to hear a four-beat count-in, then playback and capture begin. Taps during the count-in only audition, and the metronome runs until recording ends. With QUANT on, hits snap to the steps; with it off the hit offset is kept. The SWING switch enables or bypasses swing, and AMOUNT keeps its value. Quantize affects only newly captured notes. Turning a SYNTH knob also writes a parameter lock. Press R again to end recording and return to step editing while playback continues. STOP ends playback and returns to the steps; during a count-in, R or STOP cancels it. Turning REC on while playing restarts from a four-beat count-in.</p></article><article><b>U / MUTE</b><p>Mutes the current track. SHIFT + U enters mute performance, where number keys or panel buttons toggle each track's mute; press SHIFT + U again to leave.</p></article></div></section>
<section><h3>04 / A different sound on every step</h3><div class="manualFlow"><span>Hold a STEP</span><b>+</b><span>drag / scroll a knob</span><b>→</b><span>that step's locked value</span></div><p>You can also select a step, press <kbd>L</kbd> to turn STEP LOCK on, then turn a SYNTH knob. Locked parameters apply to that one step only; <kbd>ESC</kbd> exits the lock, and CLEAR LOCKS on the panel removes every lock on the selected step. With nothing locked, the knobs edit the current track's sound.</p><p><b>STORE → twist everything → RELOAD:</b> saves and restores the Kit sounds and FX. RELOAD keeps the patterns, parameter locks and mute states, and playback keeps running — ideal for making live changes and then coming back.</p></section>
<section><h3>05 / FX signal path</h3><div class="manualFlow"><span>current track<small>dry, straight out</small></span><b>→</b><span>A / D.SEND<br>B / R.SEND<small>per-track send level</small></span><b>→</b><span>DELAY / REVERB<small>C–G global parameters</small></span><b>→</b><span>OUTPUT</span></div><p>Click FX on the centre screen and the right-hand knobs switch pages with it. Raise the A or B send first, then trim the effect — with return level but no send level you will hear no wet signal. FX is a track / global setting and is never written into per-step parameter locks.</p><div class="manualFx"><span><b>A</b>D.SEND · delay send</span><span><b>B</b>R.SEND · reverb send</span><span><b>C</b>TIME · delay time / ms</span><span><b>D</b>FDBK · delay feedback</span><span><b>E</b>D.RET · delay return</span><span><b>F</b>DECAY · reverb length / s</span><span><b>G</b>R.RET · reverb return</span><span><b>H</b>unassigned</span></div></section>
<section><h3>06 / Shortcut reference</h3><div class="manualShortcuts"><span><kbd>SPACE</kbd>play / stop</span><span><kbd>ENTER</kbd>audition the current sound</span><span><kbd>← →</kbd>previous / next step</span><span><kbd>↑ ↓</kbd>SYNTH pitch / FX send A</span><span><kbd>L</kbd>per-step parameter lock</span><span><kbd>ESC</kbd>exit the lock / close the manual</span></div><p>Knobs respond to vertical dragging and to the scroll wheel; when a knob has focus, the arrow keys trim it, HOME / END jump to minimum / maximum, and double-click auditions. While an input box is being edited, the performance shortcuts stay out of the way.</p><p class="manualNote">Editing is auto-saved to this browser. While the manual is open, the performance shortcuts pause and the music keeps playing. Close it with the × at the top right, a click outside, or ESC.</p></section></div>`;
document.body.append(manual);
document.querySelector('#info').onclick = () => manual.showModal();
document.querySelector('#closeManual').onclick = () => manual.close();
manual.addEventListener('click', (e) => {
  if (e.target === manual) {
    const r = manual.getBoundingClientRect();
    if (e.clientX < r.left || e.clientX > r.right || e.clientY < r.top || e.clientY > r.bottom)
      manual.close();
  }
});
